export const sounds = [
    {
        name: 'Ho ho ho!',
        type: 'sprite',
        file: [
            '/assets/sounds/Ho ho ho.mp3', 
            '/assets/sounds/Ho ho ho 2.mp3',
        ],
        icon: '/assets/images/beard.png',
        altText: 'Santa beard',
    },
    {
        name: 'Reindeer',
        type: 'sprite',
        file: [
            '/assets/sounds/Dog bark.mp3', 
            '/assets/sounds/Meow.mp3',
            '/assets/sounds/Moo.mp3',
        ],
        icon: '/assets/images/deer.png',
        altText: 'Santa beard',
    },
    {
        name: 'Sleigh bells',
        type: 'sprite',
        file: [
            '/assets/sounds/Sleigh bells.mp3', 
        ],
        icon: '/assets/images/sled.png',
        altText: 'Santa sleigh',
    },
    {
        name: 'Bon bon',
        type: 'sprite',
        file: [
            '/assets/sounds/Bon bon.mp3', 
            '/assets/sounds/Bon bon 2.mp3', 
        ],
        icon: '/assets/images/cracker.png',
        altText: 'Bon bon',
    },
    {
        name: 'Fireplace',
        type: 'track',
        file: '/assets/sounds/Fireplace.mp3',
        icon: '/assets/images/fireplace.png',
        altText: 'Fireplace',
    },
    {
        name: 'Relaxing Christmas music',
        type: 'track',
        file: '/assets/sounds/Joy to the World.mp3',
        icon: '/assets/images/christmas-music.png',
        altText: 'House with music notes',
    },
    {
        name: 'Opening presents',
        type: 'track',
        file: '/assets/sounds/Wrapping paper.mp3',
        icon: '/assets/images/gift.png',
        altText: 'Wrapped present',
    },
    {
        name: 'Eating Christmas lunch',
        type: 'track',
        file: '/assets/sounds/Eating.mp3',
        icon: '/assets/images/turkey-leg.png',
        altText: 'Turkey',
    },
    {
        name: 'Last-minute Christmas shopping',
        type: 'track',
        file: '/assets/sounds/Medieval battle.mp3',
        icon: '/assets/images/shopping-bag.png',
        altText: 'Shopping bag',
    },
    {
        name: 'The best present ever',
        type: 'track',
        file: '/assets/sounds/Nintendo Sixty FOOOOOOOOOOUR.mp3',
        icon: '/assets/images/nintendo-64.png',
        altText: 'Nintendo 64 logo',
    },
    {
        name: 'Playing with the best present ever',
        type: 'track',
        file: '/assets/sounds/Super Mario 64.mp3',
        icon: '/assets/images/mario.png',
        altText: 'Mario',
    },
]